### ISSUE TITLE
TV series

### ISSUE THREAD

**Issue by Nemcio** [taobataoma/meanTorrent#33]
I want to add a serial that has 2500 episodes and every day is a new episode.
Can you add new episodes to this series? Are there only new topics every day?
Is there an option like in collections?

**Comment by taobataoma** [comment]
@Nemcio serial data origin TMDB, if TMDB support then you can do, else can not.
your serial same as 1S and 1-2500E, you can upload echo S1Ex every day, or upload S1Ex-xxxx any day. and you can see all torrents of this serial in torrent detail page 'other torrents' panel. this is your wanted collections idea of serial.
meanTorrent is not can custom for every user, It can only meet more people's needs.

more explore more surprise

if you have more question, please put them into one topic to discuss, not a new topic for every question, you can see all are your question on one screen, and close topic is good habit

**Comment by Nemcio** [comment]
Serial not on TMDB.
See you are unhappy with your product.
These were all my suggestions.
I will not write anymore since you are angry.
I wish you a pleasant work and development of meanTorrent.

**Comment by taobataoma** [comment]
@Nemcio sorry, i am not angry, i only tell you should do more explore on demo site, maybe you can find you wanted answer, sorry again.

**Comment by nearsou** [comment]
Please @Nemcio don't take it like that, I don't think @taobataoma is angry 
also do you really think he is not enjoying what he is doing otherwise he 
would stop his work and not improve meanTorrent... ? Thing is making all this changes 
would take much time and you request too many thing, yes the cms miss some features 
but hey we are here to improve in general not for single person, please be patient and chill 👍 
also can you close all threads that already solved much appreciate :)
