### ISSUE TITLE
Public tracker

### ISSUE THREAD

**Issue by FLYBYME** [taobataoma/meanTorrent#7]
How hard world it be to convert the code to a public tracker?

**Comment by taobataoma** [comment]
@FLYBYME  meanTorrent tracker is private, But, meanTorrent CMS support public tracker torrents management  with `private_torrent_cms` set to false in `config/env/torrents.js`, in public mode, user can upload and download public tracker torrent files, but these torrent files is can not used by meanTorrent tracker server. if you want to change the source code and  make yours server support public mode, maybe no small amount of work.

**Comment by FLYBYME** [comment]
Yeah I was looking through the source code and it looks like the passkey is baked in. I might play around and see what I can come up with.

Your doing great work by the way. The project should have a lot more stars!

**Comment by taobataoma** [comment]
@FLYBYME  thanks a lot.
because this project is only three months, so there aren't many stars, if you find some good way for public tracker, let's perfect it together.

Now, I'm going to start the music torrents upload section, the movie and tv info is scrape from TMDB, but, because a song may have very many recorded or live versions, or exist in different from the album, so auto load songs info(like: [musicbrainz.org](musicbrainz.org)) is not a good idea, I think this information may have to manually enter let uploaders, do you have any good suggestions?

where r u from? Reply so soon.

**Comment by arso1er** [comment]
Hi. I'm learning web development to make some projects, and I've got to say your work is outstanding. Just wow!

For music (and other categories except movies and tv) how about letting the user enter bbcode and generate the page from it (with a parser?)?

PS: I'm new to this, so I may say stupid things. Please, bear with me.

**Comment by taobataoma** [comment]
@arso1er Hi, thanks very much. did u have any sample website with bbcode? I need learn more.

**Comment by arso1er** [comment]
I know of [yggtorrent](https://yggtorrent.com/)
But it's in french.

**Comment by taobataoma** [comment]
@arso1er thanks, let me look it.
